services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spc_project_app
    stdin_open: true
    tty: true
    working_dir: /app
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: /app/docker-entrypoint.sh
