prepare:
  columns_to_drop:
    - fnlwgt
    - education

features:
  test_size: 0.2
  random_state: 42
  drop_first: true

train:
  models: "xgboost,mlp"
  xgboost:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.9
    colsample_bytree: 0.9
    random_state: 42
  mlp:
    dropout_rate: 0.4
    learning_rate_init: 0.0001
    max_iter: 500
    batch_size: 32
    random_state: 42
