from pathlib import Path

from dotenv import load_dotenv
from loguru import logger

# Load environment variables from .env file if it exists
load_dotenv()

# Paths
PROJ_ROOT = Path(__file__).resolve().parents[1]
logger.info(f"PROJ_ROOT path is: {PROJ_ROOT}")

DATA_DIR = PROJ_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
EXTERNAL_DATA_DIR = DATA_DIR / "external"

MODELS_DIR = PROJ_ROOT / "models"

REPORTS_DIR = PROJ_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

# --- Salary dataset (Adult Census Income) specific configuration ---
TARGET_COLUMN = "salary"
POSITIVE_LABEL = ">50K"

# fnlwgt: census sampling weight, not a predictive feature.
# education: redundant with the already numeric/ordinal education-num.
COLUMNS_TO_DROP = ["fnlwgt", "education"]

# Columns whose raw "?" values (parsed as NaN by CSVDataLoader) are
# imputed with their mode.
CATEGORICAL_COLUMNS_TO_IMPUTE = ["workclass", "occupation", "native-country"]

# Continuous numerical columns that must be standardized. IMPORTANT:
# the one-hot dummy columns generated by OneHotCategoricalEncoder are
# intentionally excluded here -- they are already 0/1 and scaling them
# would distort their meaning (see StandardNumericalScaler).
NUMERICAL_COLUMNS = ["age", "education-num", "capital-gain", "capital-loss", "hours-per-week"]

# --- MLflow experiment tracking ---
# MLflow 3.x deprecated the plain filesystem backend ("file:./mlruns");
# a local SQLite database is now the recommended lightweight backend.
MLFLOW_TRACKING_URI = f"sqlite:///{(PROJ_ROOT / 'mlflow.db').as_posix()}"
MLFLOW_EXPERIMENT_NAME = "salary-classification"

# If tqdm is installed, configure loguru with tqdm.write
# https://github.com/Delgan/loguru/issues/135
try:
    from tqdm import tqdm

    logger.remove(0)
    logger.add(lambda msg: tqdm.write(msg, end=""), colorize=True)
except ModuleNotFoundError:
    pass
